[build]
  command = "rm -rf node_modules package-lock.json && npm install && cat node_modules/@astrojs/sitemap/package.json | grep version && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  NODE_OPTIONS = "--max-old-space-size=4096"
